### ISSUE TITLE
BaseORMService.merge doesn't seem to merge entities back into session

### ISSUE THREAD

**Issue by Tyf0x** [ColdBox/cbox-cborm#10]
Using the merge function doesn't seems to attach the specified entity to the session.

[```BaseORMService.merge(entity)```](https://github.com/ColdBox/cbox-cborm/blame/master/modules/cborm/models/BaseORMService.cfc#L964) is using Coldfusion's entityMerge which returns a new object attached to the session. However, the original object passed as an argument [will not be attached](http://help.adobe.com/en_US/ColdFusion/9.0/CFMLRef/WSfd7453be0f56bba437188258123092b394c-7fff.html).

Did I do something wrong or misunderstood how the framework is working?

On a side note, the doc [specifies](https://github.com/ColdBox/cbox-cborm/wiki/merge) that the [merge()](https://github.com/ColdBox/cbox-cborm/blame/master/modules/cborm/models/BaseORMService.cfc#L964) function returns void which isn't correct.

**Comment by Tyf0x** [comment]
@lmajano Is this a bug or am I using it wrong?

**Comment by lmajano** [comment]
Hmm as far as I see from the docs the entity should be attached to the hibernate session. I believe there is no return from the entity merge since the objects are passed by reference. What if you do this manually?

Luis Majano
CEO
Ortus Solutions, Corp
www.ortussolutions.com
P/F: 1-888-557-8057




On Thu, Feb 25, 2016 at 7:25 PM -0800, "Tyf0x" <notifications@github.com> wrote:












@lmajano Is this a bug or am I using it wrong?

**Comment by Tyf0x** [comment]
According to the coldfusion doc:

"It copies the state of the given object onto the persistent object with the same identifier **and returns the persistent object**.

If there is no persistent instance currently associated with the session, it is loaded. **The given instance is not associated with the session. User have to use the returned object from this session**."

**Comment by lmajano** [comment]
Weird. Ok. I think we need a ticket to address this then. 

Luis Majano
CEO
Ortus Solutions, Corp
www.ortussolutions.com
P/F: 1-888-557-8057




On Thu, Feb 25, 2016 at 10:21 PM -0800, "Tyf0x" <notifications@github.com> wrote:












According to the coldfusion doc:



"It copies the state of the given object onto the persistent object with the same identifier and returns the persistent object.



If there is no persistent instance currently associated with the session, it is loaded. The given instance is not associated with the session. User have to use the returned object from this session."

**Comment by Tyf0x** [comment]
Does this github issue not count as a ticket?

If not, where should I create a ticket?

**Comment by lmajano** [comment]
I am sorry, that's right. I forget, since we have so much stuff in Jira.  I will mark this ticket.
